# This file was generated by GoReleaser. DO NOT EDIT.
cask "freight" do
  name "freight"
  desc "Freight is a zero-dependency Git hook orchestrator that replaces fragile scripts with a high-performance Go binary and a single, declarative JSON manifest."
  homepage "https://github.com/devbytes-cloud/freight"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "freight"

  on_macos do
    on_intel do
      url "https://github.com/devbytes-cloud/freight/releases/download/v#{version}/freight_Darwin_x86_64.tar.gz",
        verified: "github.com/devbytes-cloud/freight"
      sha256 "336958eb050a817fc806d9675107bc4aa359f0eb563b97955b0dcb6446ef99e9"
    end
    on_arm do
      url "https://github.com/devbytes-cloud/freight/releases/download/v#{version}/freight_Darwin_arm64.tar.gz",
        verified: "github.com/devbytes-cloud/freight"
      sha256 "835ed741a1f614a02ec908149c8d1df7fe4009f33d67d83946e120e11ee22993"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devbytes-cloud/freight/releases/download/v#{version}/freight_Linux_x86_64.tar.gz",
        verified: "github.com/devbytes-cloud/freight"
      sha256 "bb390a59929fe867a62d94f3e5c8600fddddc2b7dc8fc929a4d8edc7c552d42f"
    end
    on_arm do
      url "https://github.com/devbytes-cloud/freight/releases/download/v#{version}/freight_Linux_arm64.tar.gz",
        verified: "github.com/devbytes-cloud/freight"
      sha256 "0d23d1f7ef7064bc10393fda6c93c23c15a163d6bdd7fe81ca040cee46c48ddd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/freight"]
    end
  end

  # No zap stanza required
end
