# This file was generated by GoReleaser. DO NOT EDIT.
cask "freight" do
  name "freight"
  desc "Freight is a zero-dependency Git hook orchestrator that replaces fragile scripts with a high-performance Go binary and a single, declarative JSON manifest."
  homepage "https://github.com/devbytes-cloud/freight"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "freight"

  on_macos do
    on_intel do
      url "https://github.com/devbytes-cloud/freight/releases/download/v#{version}/freight_Darwin_x86_64.tar.gz",
        verified: "github.com/devbytes-cloud/freight"
      sha256 "ece0f94bf2b8317053168c4378ef7ec535b5e1e149cdfa919a201c8094ae9122"
    end
    on_arm do
      url "https://github.com/devbytes-cloud/freight/releases/download/v#{version}/freight_Darwin_arm64.tar.gz",
        verified: "github.com/devbytes-cloud/freight"
      sha256 "7ddf8b38999375192e7490c4020343b331e6c0bc6e61e0456d174f3be8fc2fe7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devbytes-cloud/freight/releases/download/v#{version}/freight_Linux_x86_64.tar.gz",
        verified: "github.com/devbytes-cloud/freight"
      sha256 "abbd7a12dc3faec02c88e07b4789a5d6d09f1cacbb0a7b4eefdee5c9f4204393"
    end
    on_arm do
      url "https://github.com/devbytes-cloud/freight/releases/download/v#{version}/freight_Linux_arm64.tar.gz",
        verified: "github.com/devbytes-cloud/freight"
      sha256 "c83a3ada6bcab4a121a5210de94e0cef4e77c9636509eabdebad538f48003440"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/freight"]
    end
  end

  # No zap stanza required
end
