# This file was generated by GoReleaser. DO NOT EDIT.
cask "freight" do
  name "freight"
  desc "Freight is a zero-dependency Git hook orchestrator that replaces fragile scripts with a high-performance Go binary and a single, declarative JSON manifest."
  homepage "https://github.com/devbytes-cloud/freight"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "freight"

  on_macos do
    on_intel do
      url "https://github.com/devbytes-cloud/freight/releases/download/v#{version}/freight_Darwin_x86_64.tar.gz",
        verified: "github.com/devbytes-cloud/freight"
      sha256 "4f64ead799af28e6901dc375bb7fd4fac5f4bf33b0fc82ef3c7c4ecf7badc94b"
    end
    on_arm do
      url "https://github.com/devbytes-cloud/freight/releases/download/v#{version}/freight_Darwin_arm64.tar.gz",
        verified: "github.com/devbytes-cloud/freight"
      sha256 "ce871ec7d8eb4189a3953fface9eb916cf1bd1f0dae499504cc3c72c1b4ff5f4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devbytes-cloud/freight/releases/download/v#{version}/freight_Linux_x86_64.tar.gz",
        verified: "github.com/devbytes-cloud/freight"
      sha256 "bbbd2ae76061bd00f15bd5b67f409b20458fe85ee19d6d3349ce4cce6c0ffbce"
    end
    on_arm do
      url "https://github.com/devbytes-cloud/freight/releases/download/v#{version}/freight_Linux_arm64.tar.gz",
        verified: "github.com/devbytes-cloud/freight"
      sha256 "e0e83e40cdda92e3046a1cf86d8938059fcbae5d237020ea0229a386528238a3"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/freight"]
    end
  end

  # No zap stanza required
end
