# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conditioner < Formula
  desc "Conditioner plugin allows you to add, update, or remove conditions on Kubernetes nodes"
  homepage "https://github.com/devbytes-cloud/conditioner"
  version "1.2.1"
  license "Apache-2.0 license"

  on_macos do
    on_intel do
      url "https://github.com/devbytes-cloud/conditioner/releases/download/v1.2.1/conditioner_Darwin_x86_64.tar.gz"
      sha256 "5a3fd1f0e7d0a7b4a3b2134671752a88a056110524437711374c80a6dd014907"

      def install
        bin.install "kubectl-conditioner" => "conditioner"
      end
    end
    on_arm do
      url "https://github.com/devbytes-cloud/conditioner/releases/download/v1.2.1/conditioner_Darwin_arm64.tar.gz"
      sha256 "891b9c83140b72e8ca3b7357e37725aa2c1712bfaf681984caeeb6183783e34d"

      def install
        bin.install "kubectl-conditioner" => "conditioner"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devbytes-cloud/conditioner/releases/download/v1.2.1/conditioner_Linux_x86_64.tar.gz"
        sha256 "08f740fe0a749567220cec1db51da964341e3fe53dc39f0c9bb6dccd65abdd19"

        def install
          bin.install "kubectl-conditioner" => "conditioner"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/devbytes-cloud/conditioner/releases/download/v1.2.1/conditioner_Linux_armv6.tar.gz"
        sha256 "352a81fc49185431bab37906eddcc3b30be4d4e7c6692b62220fff318a310267"

        def install
          bin.install "kubectl-conditioner" => "conditioner"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devbytes-cloud/conditioner/releases/download/v1.2.1/conditioner_Linux_arm64.tar.gz"
        sha256 "35d17a18b4c462c99cc44ea4d2da82399d4643295be1fb1ffcbf52480ab66184"

        def install
          bin.install "kubectl-conditioner" => "conditioner"
        end
      end
    end
  end
end
