# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conditioner < Formula
  desc "Conditioner plugin allows you to add, update, or remove conditions on Kubernetes nodes"
  homepage "https://github.com/devbytes-cloud/conditioner"
  version "1.0.1"
  license "Apache-2.0 license"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devbytes-cloud/conditioner/releases/download/v1.0.1/conditioner_Darwin_arm64.tar.gz"
      sha256 "f50e92004d8109c54eb872faab73010e0ed61a02d56486aad5bede42886dccc3"

      def install
        bin.install "kubectl-conditioner" => "conditioner"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devbytes-cloud/conditioner/releases/download/v1.0.1/conditioner_Darwin_x86_64.tar.gz"
      sha256 "80c63c39b89e67bf66e802c2a1d868bccc5d8afd2614fcce691f2f15c34b4054"

      def install
        bin.install "kubectl-conditioner" => "conditioner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/devbytes-cloud/conditioner/releases/download/v1.0.1/conditioner_Linux_armv6.tar.gz"
      sha256 "dd11356b3bd19b1478f0106002b14c30d334947add9e750f1c80e837f0ade976"

      def install
        bin.install "kubectl-conditioner" => "conditioner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devbytes-cloud/conditioner/releases/download/v1.0.1/conditioner_Linux_arm64.tar.gz"
      sha256 "40f336361822c763da28677b04ffb948523f112adc28dfff8ae60cb17a4ae8c0"

      def install
        bin.install "kubectl-conditioner" => "conditioner"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devbytes-cloud/conditioner/releases/download/v1.0.1/conditioner_Linux_x86_64.tar.gz"
      sha256 "6e08854103920465095469a2a2014df193c169a400d927e7a9265788a74a15a3"

      def install
        bin.install "kubectl-conditioner" => "conditioner"
      end
    end
  end
end
